#!/bin/bash
echo "-----------------------------------"
echo "Tugas 1 Sisop Kelas A"
echo "-----------------------------------"
echo "Nama: Meisya Vira Amelia"
echo "NPM : 21083010018"
echo "-----------------------------------"
echo "notes:"
echo "-----------------------------------"
echo "Halo dunia!"
echo "Ini adalah skrip Bash pertamaku di linux"
